const PROVINCE_MAP = {
  'Xinjiang Uygur Zizhiqu': '新疆',
  'Yunnan': '云南',
  'Tibet Autonomous Region': '西藏',
  'Qinghai Sheng': '青海',
  'Sichuan Sheng': '四川',
  'Jiangsu Sheng': '江苏',
  'Guizhou Sheng': '贵州',
  'Anhui Sheng': '安徽',
  'Gansu Sheng': '甘肃',
  'Shanxi Sheng': '山西',
  'Hubei': '湖北',
  'Hunan': '湖南',
  'Hebei': '河北',
  'Henan Sheng': '河南',
  'Shanghai Shi': '上海',
  'Zhejiang Sheng': '浙江',
  'Chongqing Shi': '重庆',
  'Shaanxi': '陕西',
  'Fujian': '福建',
  'Tianjin Shi': '天津',
  'Hainan': '海南',
  'Guangdong': '广东',
  'Jiangxi Sheng': '江西',
  'Shandong Sheng': '山东',
  'Guangxi Zhuangzu Zizhiqu': '广西',
  'Ningxia Huizu Zizhiqu': '宁夏',
  'Inner Mongolia': '内蒙古',
  'Beijing Shi': '北京',
  'Liaoning': '辽宁',
  'Heilongjiang Sheng': '黑龙江',
  'Jilin Sheng': '吉林',
  'Taiwan': '台湾',
  'Hong Kong': '香港',
  'Macao': '澳门'
}

export default PROVINCE_MAP
